<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
                             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.thunderforce</groupId>
        <artifactId>thunderforce</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>thunderforce-web</artifactId>
    <name>Thunderforce Web</name>
    <packaging>war</packaging>

    <properties>
        <gwt.version>2.11.0</gwt.version>
        <webapp.targetDir>${project.build.directory}/thunderforce-web</webapp.targetDir>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <maven.compiler.release>11</maven.compiler.release>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.thunderforce</groupId>
            <artifactId>thunderforce-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-backend-gwt</artifactId>
            <version>${gdx.version}</version>
        </dependency>
        <dependency>
            <groupId>org.gwtproject</groupId>
            <artifactId>gwt-dev</artifactId>
            <version>${gwt.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>thunderforce</finalName>
        <plugins>
            <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>1.1.0</version>
                <extensions>true</extensions>
                <configuration>
                    <moduleName>com.thunderforce.web.Web</moduleName>
                    <localWorkers>2</localWorkers>
                    <style>OBF</style>
                    <compileReport>true</compileReport>
                </configuration>
                <executions>
                    <execution>
                        <id>gwt-compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>11.0.24</version>
                <configuration>
                    <scanIntervalSeconds>5</scanIntervalSeconds>
                    <webAppSourceDirectory>${webapp.targetDir}</webAppSourceDirectory>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-war-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <warSourceDirectory>${webapp.targetDir}</warSourceDirectory>
                    <failOnMissingWebXml>false</failOnMissingWebXml>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>3.7.1</version>
                <executions>
                    <execution>
                        <id>extract-gdx-backend-gwt-theme</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.badlogicgames.gdx</groupId>
                                    <artifactId>gdx-backend-gwt</artifactId>
                                    <version>${gdx.version}</version>
                                    <classifier>sources</classifier>
                                    <type>jar</type>
                                    <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                                    <includes>com/badlogic/gdx/backends/gwt/theme/**</includes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                    <execution>
                        <id>extract-gdx-sources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.badlogicgames.gdx</groupId>
                                    <artifactId>gdx</artifactId>
                                    <version>${gdx.version}</version>
                                    <classifier>sources</classifier>
                                    <type>jar</type>
                                    <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                    <execution>
                        <id>extract-gdx-backend-gwt-sources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>unpack</goal>
                        </goals>
                        <configuration>
                            <artifactItems>
                                <artifactItem>
                                    <groupId>com.badlogicgames.gdx</groupId>
                                    <artifactId>gdx-backend-gwt</artifactId>
                                    <version>${gdx.version}</version>
                                    <classifier>sources</classifier>
                                    <type>jar</type>
                                    <outputDirectory>${project.build.outputDirectory}</outputDirectory>
                                    <includes>com/badlogic/gdx/backends/gwt/**</includes>
                                    <excludes>**/emu/**,**/theme/**,**/PreloaderBundleGenerator.java,**/FileWrapper.java</excludes>
                                </artifactItem>
                            </artifactItems>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.3.1</version>
                <executions>
                    <execution>
                        <id>copy-core-sources</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.basedir}/src/main/java</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/../core/src/main/java</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-core-assets</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${webapp.targetDir}/assets</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>${project.basedir}/../core/src/main/resources</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-webapp</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${webapp.targetDir}</outputDirectory>
                            <resources>
                                <resource>
                                    <directory>src/main/webapp</directory>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
